baseURL = "/"
languageCode = "en-uk"
title = "Beyond Measure"
theme = "m10c"
paginate = 6

[permalinks]
    posts = "/posts/:title/"

[params]
    author = "Dumky de Wilde"
    subTitle = "Dumky de Wilde"
    description = "Hey! I'm Dumky, analytics engineer from Amsterdam. I've been building websites since I was 9 years old and you can find me talking about Google Tag Manager, analytics, cloud platforms, security, JavaScript, automated testing, online marketing ethics and —every now and then— my philosophy education."
    avatar = "/turtle.svg"
    menu_item_separator = "|"
    gtm_id = "GTM-WP7XMQL"
    gtm_datalayer = "basic"
    gtm_endpoint = "https://gtm.dumky.net"
    [params.style]
        darkestColor = "#240800"
        darkColor = "#691100"
        lightColor = "#FFDBD1"
        lightestColor = "#FFF8F6"
        primaryColor = "#FA3600"
    [[params.social]]
        icon = "github"
        name = "Github"
        url = "https://github.com/dumkydewilde"
    
    [[params.social]]
        icon = "twitter"
        name = "Twitter"
        url = "https://twitter.com/dumkydewilde"
    
    [[params.social]]
        icon = "linkedin"
        name = "LinkedIn"
        url = "https://www.linkedin.com/in/dumkydewilde/"

[menu]
    [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"

[markup]
  [markup.highlight]
    guessSyntax = true
    style = "dracula"
    tabWidth = 4