baseURL = "/"
languageCode = "en-uk"
title = "Beyond Measure"
theme = "m10c"
paginate = 6

[permalinks]
    posts = "/posts/:title/"

[params]
    author = "Dumky de Wilde"
    subTitle = "Dumky de Wilde"
    description = """Hey! I'm Dumky, analytics engineer. 
        I've spent the first half of my working life in web analytics turning Google Tag Manager (GTM) inside out.
        Nowadays I spend most of my time dusting off old data models 
        and scrubbing ingestion pipelines clean in distributed data platforms."""
    avatar = "/turtle.svg"
    menu_item_separator = "|"
    gtm_id = "GTM-WP7XMQL"
    gtm_datalayer = "basic"
    gtm_endpoint = "https://gtm.dumky.net"
    snowplow_endpoint = "https://snow.dumky.net"
    [params.style]
        darkestColor = "#240800"
        darkColor = "#691100"
        lightColor = "#FFDBD1"
        lightestColor = "#FFF8F6"
        primaryColor = "#FA3600"
    [[params.social]]
        icon = "github"
        name = "Github"
        url = "https://github.com/dumkydewilde"
    
    [[params.social]]
        icon = "twitter"
        name = "Twitter"
        url = "https://twitter.com/dumkydewilde"
    
    [[params.social]]
        icon = "linkedin"
        name = "LinkedIn"
        url = "https://www.linkedin.com/in/dumkydewilde/"

[menu]
    [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"

[markup]
  [markup.highlight]
    guessSyntax = true
    style = "dracula"
    tabWidth = 4