baseURL = "https://www.dumky.net"
languageCode = "en-uk"
title = "Beyond Measure"
theme = ["m10c"]
paginate = 10

[permalinks]
    posts = "/posts/:title/"

[params]
    author = "Dumky de Wilde"
    description = ""
    avatar = "/turtle.svg"
    menu_item_separator = "|"
    gtm_id = "GTM-WP7XMQL"
    gtm_datalayer = "basic"
    gtm_endpoint = "https://gtm.dumky.net"
    snowplow_endpoint = "https://www.dumky.net"
    thumbs_up_description = "Wow, you made it all the way down, let me know if you liked it!"
    [params.style]
        darkestColor = "#240800"
        darkColor = "#691100"
        lightColor = "#FFDBD1"
        lightestColor = "#FFF8F6"
        primaryColor = "#FA3600"

    [[params.social]]
        subset = "brands"
        icon = "github"
        name = "Github"
        url = "https://github.com/dumkydewilde"
    
    [[params.social]]
        subset = "brands"
        icon = "twitter"
        name = "Twitter"
        url = "https://twitter.com/dumkydewilde"
    
    [[params.social]]
        subset = "brands"
        icon = "linkedin"
        name = "LinkedIn"
        url = "https://www.linkedin.com/in/dumkydewilde/"

    [[params.social]]
        subset = "brands"
        icon = "slack"
        name = "Measure Slack"
        url = "https://www.measure.chat/"

    [[params.social]]
        subset = "solid"
        icon = "mug-hot"
        name = "Buy Me A Coffee"
        url = "https://www.buymeacoffee.com/dumky"

[menu]
    [[menu.main]]
    identifier = "analytics"
    name = "Analytics"
    url = "/analytics/"
    
    [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"

    [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"

[markup]
  [markup.highlight]
    guessSyntax = true
    style = "dracula"
    tabWidth = 4
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
