name: Jobs
on:
    workflow_dispatch:
    push:
        branches:
            - main
            
jobs:
  consentcrawler:
    runs-on: ubuntu-latest
    container: mcr.microsoft.com/playwright/python:next-jammy-amd64

    steps:
        - uses: actions/checkout@v4
        - run: pip install consentcrawl
        - name: check unconsented tracking domains
          run: |
            output=$(consentcrawl dumky.net -o | jq '.[] | .tracking_domains_no_consent')
            if [[ "$output" != "[]" ]]; then
            echo "Tracking domains found without consent"
            echo "Output: $output"
            exit 1
            else
            echo "No tracking domains found without consent"
            fi